# NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

## 1. Creating arrays

### 1.1. Manual construction of arrays

#### 1-D

In [2]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [3]:
a.ndim # number of dimensions

1

In [4]:
a.shape

(4,)

In [5]:
len(a)

4

#### 2-D, 3-D

In [6]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [9]:
len(b) # size of first dimension

2

In [10]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [11]:
c.shape

(2, 2, 1)